# House price prediction using Linear Regression

Basic feature engineering steps has been done by using Excel.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [2]:
df = pd.read_csv('property_listing_data_in_Bangladesh.csv')
df

,title,beds,bath,area_sqft,address,type,purpose,flooPlan,url,lastUpdated,price,beds x bath
0,Eminent Apartment Of 2200 Sq Ft Is Vacant For ...,3,4,2200.0,"Block A, Bashundhara R-A, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/10...,https://www.bproperty.com/en/property/details-...,13-Aug-22,50 Thousand,12
1,"Apartment Ready To Rent In South Khulshi, Near...",3,4,1400.0,"South Khulshi, Khulshi, Chattogram",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/44...,https://www.bproperty.com/en/property/details-...,25-Jan-22,30 Thousand,12
2,"Smartly priced 1950 SQ FT apartment, that you ...",3,4,1950.0,"Block F, Bashundhara R-A, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/11...,https://www.bproperty.com/en/property/details-...,22-Feb-23,30 Thousand,12
3,2000 Sq Ft Residential Apartment Is Up For Ren...,3,3,2000.0,"Sector 9, Uttara, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/14...,https://www.bproperty.com/en/property/details-...,28-Oct-21,35 Thousand,9
4,Strongly Structured This 1650 Sq. ft Apartment...,3,4,1650.0,"Block I, Bashundhara R-A, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/10...,https://www.bproperty.com/en/property/details-...,19-Feb-23,25 Thousand,12
...,...,...,...,...,...,...,...,...,...,...,...,...
7552,"Picture Yourself, Residing In This Well Constr...",4,4,3600.0,"Sector 3, Uttara, Dhaka",Duplex,For Rent,https://images-cdn.bproperty.com/thumbnails/15...,https://www.bproperty.com/en/property/details-...,7-Feb-23,80 Thousand,16
7553,Flat For Rent In Uttara Sector 13 Near Lubana ...,3,2,900.0,"Sector 13, Uttara, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/15...,https://www.bproperty.com/en/property/details-...,9-Feb-22,19 Thousand,6
7554,1000 SQ FT flat for rent in Uttara Sector 13 n...,2,2,1000.0,"Sector 13, Uttara, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/12...,https://www.bproperty.com/en/property/details-...,14-Feb-22,22 Thousand,4
7555,Well Planned Apartment For Rent In Gulshan 1 N...,3,4,3600.0,"Gulshan 1, Gulshan, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/30...,https://www.bproperty.com/en/property/details-...,7-Feb-23,1.75 Lakh,12
7556,An Apartment Is Ready For Rent At Baridhara DO...,4,4,2600.0,"Baridhara DOHS, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/15...,https://www.bproperty.com/en/property/details-...,22-Nov-21,90 Thousand,16

In [3]:
# Specify the columns to keep
columns_to_keep = ['beds x bath','area_sqft','address', 'type', 'price']
df = df[columns_to_keep]
df

,beds x bath,area_sqft,address,type,price
0,12,2200.0,"Block A, Bashundhara R-A, Dhaka",Apartment,50 Thousand
1,12,1400.0,"South Khulshi, Khulshi, Chattogram",Apartment,30 Thousand
2,12,1950.0,"Block F, Bashundhara R-A, Dhaka",Apartment,30 Thousand
3,9,2000.0,"Sector 9, Uttara, Dhaka",Apartment,35 Thousand
4,12,1650.0,"Block I, Bashundhara R-A, Dhaka",Apartment,25 Thousand
...,...,...,...,...,...
7552,16,3600.0,"Sector 3, Uttara, Dhaka",Duplex,80 Thousand
7553,6,900.0,"Sector 13, Uttara, Dhaka",Apartment,19 Thousand
7554,4,1000.0,"Sector 13, Uttara, Dhaka",Apartment,22 Thousand
7555,12,3600.0,"Gulshan 1, Gulshan, Dhaka",Apartment,1.75 Lakh
7556,16,2600.0,"Baridhara DOHS, Dhaka",Apartment,90 Thousand

In [4]:
# Define a function to convert the string value to a numerical value
def convert_price_to_number(price):
    if 'Thousand' in price:
        return float(price.replace('Thousand', '')) * 1000
    elif 'Lakh' in price:
        return float(price.replace('Lakh', '')) * 100000
    else:
        return float(price)

# Apply the function to the 'Price' column to convert it to numerical values
df['price'] = df['price'].apply(convert_price_to_number)
df

C:\Users\ahs95\AppData\Local\Temp\ipykernel_12508\3541976426.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price'] = df['price'].apply(convert_price_to_number)

,beds x bath,area_sqft,address,type,price
0,12,2200.0,"Block A, Bashundhara R-A, Dhaka",Apartment,50000.0
1,12,1400.0,"South Khulshi, Khulshi, Chattogram",Apartment,30000.0
2,12,1950.0,"Block F, Bashundhara R-A, Dhaka",Apartment,30000.0
3,9,2000.0,"Sector 9, Uttara, Dhaka",Apartment,35000.0
4,12,1650.0,"Block I, Bashundhara R-A, Dhaka",Apartment,25000.0
...,...,...,...,...,...
7552,16,3600.0,"Sector 3, Uttara, Dhaka",Duplex,80000.0
7553,6,900.0,"Sector 13, Uttara, Dhaka",Apartment,19000.0
7554,4,1000.0,"Sector 13, Uttara, Dhaka",Apartment,22000.0
7555,12,3600.0,"Gulshan 1, Gulshan, Dhaka",Apartment,175000.0
7556,16,2600.0,"Baridhara DOHS, Dhaka",Apartment,90000.0

In [5]:
#feature_scaling
scaler = StandardScaler()
df['area_sqft'] = scaler.fit_transform(df[['area_sqft']])
df

C:\Users\ahs95\AppData\Local\Temp\ipykernel_12508\797509333.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['area_sqft'] = scaler.fit_transform(df[['area_sqft']])

,beds x bath,area_sqft,address,type,price
0,12,0.865455,"Block A, Bashundhara R-A, Dhaka",Apartment,50000.0
1,12,0.029241,"South Khulshi, Khulshi, Chattogram",Apartment,30000.0
2,12,0.604138,"Block F, Bashundhara R-A, Dhaka",Apartment,30000.0
3,9,0.656402,"Sector 9, Uttara, Dhaka",Apartment,35000.0
4,12,0.290558,"Block I, Bashundhara R-A, Dhaka",Apartment,25000.0
...,...,...,...,...,...
7552,16,2.328830,"Sector 3, Uttara, Dhaka",Duplex,80000.0
7553,6,-0.493392,"Sector 13, Uttara, Dhaka",Apartment,19000.0
7554,4,-0.388866,"Sector 13, Uttara, Dhaka",Apartment,22000.0
7555,12,2.328830,"Gulshan 1, Gulshan, Dhaka",Apartment,175000.0
7556,16,1.283562,"Baridhara DOHS, Dhaka",Apartment,90000.0

In [6]:
encoded_col = ['address', 'type']

In [7]:
#performing_one_hot_encoding
df = pd.get_dummies(data = df,
                         prefix = encoded_col,
                         columns = encoded_col)

In [8]:
df

,beds x bath,area_sqft,price,"address_1 No. South Pahartali Ward, Hathazari, Chattogram","address_10 No. North Kattali Ward, Chattogram","address_11 No. South Kattali Ward, Chattogram","address_12 No. Sarai Para Ward, Double Mooring, Chattogram","address_14 No. Lalkhan Bazaar Ward, Lal Khan Bazaar, Chattogram","address_15 No. Bagmoniram Ward, Chattogram","address_16 No. Chawk Bazaar Ward, Chattogram",...,"address_West Rampura, Rampura, Dhaka","address_West Shahid Nagar, Oxygen, Bayazid, Chattogram","address_West Shewrapara, Mirpur, Dhaka","address_Zafrabad, Dhaka","address_Zafrabad, Hazaribag, Dhaka","address_Zakir Hossain Housing Society, South Khulshi, Khulshi, Chattogram","address_aziz Moholla, Mohammadpur, Dhaka",type_Apartment,type_Building,type_Duplex
0,12,0.865455,50000.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,12,0.029241,30000.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,12,0.604138,30000.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,9,0.656402,35000.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,12,0.290558,25000.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7552,16,2.328830,80000.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7553,6,-0.493392,19000.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
7554,4,-0.388866,22000.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
7555,12,2.328830,175000.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
7556,16,1.283562,90000.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [9]:
# Split the dataset into train, validation, and test sets
train_df, remaining_df = train_test_split(df, test_size=0.4, random_state=42)
validation_df, test_df = train_test_split(remaining_df, test_size=0.5, random_state=42)

# Print the shapes of the resulting DataFrames
print("Train set shape:", train_df.shape)
print("Validation set shape:", validation_df.shape)
print("Test set shape:", test_df.shape)

Train set shape: (4534, 683)
Validation set shape: (1511, 683)
Test set shape: (1512, 683)

In [10]:
# Define the features and target variables for training and validation
train_X = train_df
train_y = train_df['price']
validation_X = validation_df
validation_y = validation_df['price']

In [11]:
# Initialize and fit the linear regression model
model = LinearRegression()
model.fit(train_X, train_y)

# Make predictions on training and validation sets
train_predictions = model.predict(train_X)
validation_predictions = model.predict(validation_X)

# Calculate the mean squared error for training and validation sets
train_mse = mean_squared_error(train_y, train_predictions)
validation_mse = mean_squared_error(validation_y, validation_predictions)

# Print the mean squared error
print("Train set MSE:", train_mse)
print("Validation set MSE:", validation_mse)

Train set MSE: 1.7150910779094587e-20
Validation set MSE: 2.1109103809240273e-08

In [12]:
test_X = test_df
test_y = test_df['price']
model.fit(test_X, test_y)
test_predictions = model.predict(test_X)
mse_test = mean_squared_error(test_y, test_predictions)
print("Mean Squared Error (MSE) - Test Set:", mse_test)

Mean Squared Error (MSE) - Test Set: 2.126449941250084e-21